### ISSUE TITLE
<nuxt-link> in markdown

### ISSUE THREAD

**Issue by delucis** [nuxt-community/markdownit-module#16]
I’m using the `markdown-it` module, and wanted to see if it would be possible to render links as `<nuxt-link>` tags. 

markdown             | html
----------------|----------------------------------------
`[About](/about)` | `<nuxt-link to="/about">About</nuxt-link>`

I managed to do that by setting `md.renderer.rules` for `link_open` and `link_close`, which produces HTML including `<nuxt-link>` tags, but when rendered using `v-html`, Vue/Nuxt doesn’t pick up any included components.

Where would I have to do the markdown rendering in order for those to be processed properly? Or is there an existing solution?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/modules/issues/c106">#c106</a>)</em></sub></div>

**Comment by d-darwin** [comment]
> > > The link is broken.
> > 
> > 
> > @d-darwin
> > https://github.com/nuxt/nuxtjs.org/blob/master/components/commons/HtmlParser.global.vue
> 
> The link is broken again...help...

Try this one: https://github.com/d-darwin/darwin-vue-ui/blob/main/src/mixins/LinkClickRouting.js

**Comment by JudahGabriel** [comment]
Actual working link: https://github.com/d-darwin/darwin-vue-ui/blob/main/src/mixins/linkClickRouting.js

**Comment by arc-arnob** [comment]
> > > > The link is broken.
> > > 
> > > 
> > > @d-darwin
> > > https://github.com/nuxt/nuxtjs.org/blob/master/components/commons/HtmlParser.global.vue
> > 
> > 
> > The link is broken again...help...
> 
> Try this one: https://github.com/d-darwin/darwin-vue-ui/blob/main/src/mixins/LinkClickRouting.js

This link is broken too, help...

**Comment by the94air** [comment]
😂 all of them are broken

**Comment by Michael1337** [comment]
Take this code: https://github.com/d-darwin/darwin-vue-ui/blob/main/src/mixins/linkClickRouting.js
Copy and paste it as-is into layouts/default.vue inside the `<script>` tags. (If you have other code there already, mix them together, obviously.)
Then you can have jsons like this one: `"2": "If you want to check out some of my projects and try them out, <a href=\"/projects\" aria-label=\"Projects\" title=\"Projects\">feel free to take a look</a>.",`
Don't try to make it a global mixin, because that would try to `getElementsByTagName` from within each element, i.e. calling the methods hundreds of times and failing on elements that don't have elements, like comments.
